import {useEffect,useState} from "react";
import SectionHeader from "../components/SectionHeader";
import DataTable from "../components/DataTable";
import FormModal from "../components/FormModal";
import {neon} from "../lib/neon";
const money=(v:any)=>"৳"+Number(v||0).toLocaleString();
export default function CashReceipts(){
 const[rows,setRows]=useState<any[]>([]),[clients,setClients]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<any>({receipt_no:"",receipt_date:"",client_id:"",project_id:"",amount:"",note:""}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const[r,c,p]=await Promise.all([neon.from("client_payments").select("*").order("receipt_date",{ascending:false}),neon.from("clients").select("id,client_code,company_name"),neon.from("projects").select("id,project_code,project_name")]);setRows(r.data||[]);setClients(c.data||[]);setProjects(p.data||[])}useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();setBusy(true);const q=await neon.from("client_payments").insert({...form,amount:Number(form.amount||0),payment_method:"CASH",status:"SUBMITTED"});if(q.error)setError(q.error.message);else{setOpen(false);await load()}setBusy(false)}
 return <div><SectionHeader eyebrow="CASH RECEIPTS" title="Client Payments" description="Record physical cash received from clients and keep it linked to projects." action={<button className="primary-btn" onClick={()=>setOpen(true)}>+ Cash Receipt</button>}/><DataTable rows={rows} columns={[{key:"receipt_no",label:"Receipt"},{key:"receipt_date",label:"Date"},{key:"client_id",label:"Client",render:(r:any)=>clients.find(c=>c.id===r.client_id)?.company_name||r.client_id},{key:"project_id",label:"Project",render:(r:any)=>projects.find(p=>p.id===r.project_id)?.project_name||"—"},{key:"amount",label:"Amount",render:(r:any)=>money(r.amount)},{key:"payment_method",label:"Method"}]}/>{open&&<FormModal title="Add Client Cash Receipt" onClose={()=>setOpen(false)} onSubmit={save} busy={busy}><label>Receipt No.<input required value={form.receipt_no} onChange={e=>setForm({...form,receipt_no:e.target.value})}/></label><label>Date<input required type="date" value={form.receipt_date} onChange={e=>setForm({...form,receipt_date:e.target.value})}/></label><label>Client<select required value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})}><option value="">Select client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.client_code} — {c.company_name}</option>)}</select></label><label>Project<select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">Optional</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} — {p.project_name}</option>)}</select></label><label>Amount<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Note<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>{error&&<div className="form-error full">{error}</div>}</FormModal>}</div>
}