import {useEffect,useState} from "react";
import SectionHeader from "../components/SectionHeader";
import DataTable from "../components/DataTable";
import FormModal from "../components/FormModal";
import {neon} from "../lib/neon";
const money=(v:any)=>"৳"+Number(v||0).toLocaleString();
export default function WorkerAdvances(){
 const[rows,setRows]=useState<any[]>([]),[workers,setWorkers]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[open,setOpen]=useState(false),[form,setForm]=useState<any>({worker_id:"",project_id:"",advance_date:"",amount:"",advance_type:"POCKET_MONEY",note:""}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const[r,w,p]=await Promise.all([neon.from("worker_advances").select("*").order("advance_date",{ascending:false}),neon.from("workers").select("id,worker_code,full_name"),neon.from("projects").select("id,project_code,project_name")]);setRows(r.data||[]);setWorkers(w.data||[]);setProjects(p.data||[])}useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();setBusy(true);const q=await neon.from("worker_advances").insert({...form,amount:Number(form.amount||0),status:"SUBMITTED"});if(q.error)setError(q.error.message);else{setOpen(false);await load()}setBusy(false)}
 return <div><SectionHeader eyebrow="WORKER CASH" title="Pocket Money / Advances" description="Daily cash advances are recorded separately and deducted during settlement." action={<button className="primary-btn" onClick={()=>setOpen(true)}>+ Add Pocket Money</button>}/><DataTable rows={rows} columns={[{key:"advance_date",label:"Date"},{key:"worker_id",label:"Worker",render:(r:any)=>workers.find(w=>w.id===r.worker_id)?.full_name||r.worker_id},{key:"project_id",label:"Project",render:(r:any)=>projects.find(p=>p.id===r.project_id)?.project_name||"—"},{key:"advance_type",label:"Type"},{key:"amount",label:"Amount",render:(r:any)=>money(r.amount)},{key:"status",label:"Status"}]}/>{open&&<FormModal title="Add Pocket Money / Advance" onClose={()=>setOpen(false)} onSubmit={save} busy={busy}><label>Worker<select required value={form.worker_id} onChange={e=>setForm({...form,worker_id:e.target.value})}><option value="">Select worker</option>{workers.map(w=><option key={w.id} value={w.id}>{w.worker_code} — {w.full_name}</option>)}</select></label><label>Project<select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">Optional</option>{projects.map(p=><option key={p.id} value={p.id}>{p.project_code} — {p.project_name}</option>)}</select></label><label>Date<input required type="date" value={form.advance_date} onChange={e=>setForm({...form,advance_date:e.target.value})}/></label><label>Amount<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Type<select value={form.advance_type} onChange={e=>setForm({...form,advance_type:e.target.value})}><option>POCKET_MONEY</option><option>ADVANCE</option><option>OTHER</option></select></label><label>Note<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label>{error&&<div className="form-error full">{error}</div>}</FormModal>}</div>
}