import {useEffect,useState} from "react";
import SectionHeader from "../components/SectionHeader";
import DataTable from "../components/DataTable";
import Badge from "../components/Badge";
import FormModal from "../components/FormModal";
import {neon} from "../lib/neon";
const empty={worker_code:"",full_name:"",phone:"",nid_no:"",category:"Mason",address:"",emergency_contact:"",default_rate:"",status:"ACTIVE",join_date:"",notes:""};
export default function Workers(){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState<any>(empty),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);const [w,a,p]=await Promise.all([neon.from("workers").select("*").order("worker_code"),neon.from("worker_assignments").select("worker_id,project_id,status").eq("status","ACTIVE"),neon.from("projects").select("id,project_name")]);const pm=Object.fromEntries((p.data||[]).map((x:any)=>[x.id,x.project_name]));const am=Object.fromEntries((a.data||[]).map((x:any)=>[x.worker_id,pm[x.project_id]||"—"]));setRows((w.data||[]).map((x:any)=>({...x,project:am[x.id]||"—"})));setLoading(false)}
 useEffect(()=>{load()},[]);
 function start(r?:any){setEdit(r||null);setForm(r?{...r,default_rate:String(r.default_rate??"")}:{...empty});setError("");setOpen(true)}
 async function save(e:any){e.preventDefault();setBusy(true);setError("");const payload={...form,default_rate:Number(form.default_rate||0)};["id","project","created_at","updated_at"].forEach(k=>delete payload[k]);const r=edit?await neon.from("workers").update(payload).eq("id",edit.id):await neon.from("workers").insert(payload);if(r.error)setError(r.error.message);else{setOpen(false);await load()}setBusy(false)}
 async function archive(r:any){if(!confirm("Worker-কে INACTIVE করবেন?"))return;const q=await neon.from("workers").update({status:"INACTIVE"}).eq("id",r.id);if(q.error)alert(q.error.message);else load()}
 const field=(k:string,label:string,req=false,type="text")=><label>{label}<input type={type} value={form[k]??""} required={req} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>;
 return <div><SectionHeader eyebrow="WORKFORCE" title="Workers" description="Live worker profiles, categories, assignments and effective rates." action={<button className="primary-btn" onClick={()=>start()}>+ Add Worker</button>}/><div className="toolbar"><input placeholder="Search worker, phone or ID..."/><select><option>All categories</option></select><select><option>All status</option></select></div>{loading?<div className="empty-state">Loading workers…</div>:<DataTable rows={rows} columns={[{key:"worker_code",label:"Worker ID"},{key:"full_name",label:"Worker",render:r=><strong>{r.full_name}</strong>},{key:"category",label:"Category"},{key:"project",label:"Current Project"},{key:"default_rate",label:"Rate / Hajira",render:r=><span>৳{Number(r.default_rate||0).toLocaleString()}</span>},{key:"status",label:"Status",render:r=><Badge tone={r.status==="ACTIVE"?"success":"neutral"}>{r.status}</Badge>},{key:"id",label:"Actions",render:r=><span className="row-actions"><button onClick={()=>start(r)}>Edit</button>{r.status==="ACTIVE"&&<button onClick={()=>archive(r)}>Inactive</button>}</span>}]}/>} {open&&<FormModal title={edit?"Edit Worker":"Add Worker"} onClose={()=>setOpen(false)} onSubmit={save} busy={busy}>{field("worker_code","Worker ID",true)}{field("full_name","Full Name",true)}{field("phone","Phone")}{field("nid_no","NID No.")}{field("category","Category",true)}{field("default_rate","Default Rate / Hajira",true,"number")}{field("join_date","Join Date",false,"date")}{field("address","Address")}{field("emergency_contact","Emergency Contact")}{field("notes","Notes")}{error&&<div className="form-error full">{error}</div>}</FormModal>}</div>
}